language: cpp
sudo: required
dist: Trusty
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
script:
  cd vector && make && cd ../stack &&  make && cd ../queue && make && cd ../list && make && cd ../algorithm && make